apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog
spec:
  global:
    clusterName: workspace-cluster
    site: "datadoghq.com"
    tags:
      - "env:dev"
      - "project:single-step"
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: "api-key"
  features:
    apm:
      instrumentation:
        enabled: true
        libVersions:
          java: "1"
          python: "2"
    logCollection:
      enabled: true
      containerCollectAll: true
    asm:
      sca:
        enabled: true
    usm:
      enabled: true
    npm:
      enabled: true
    remoteConfiguration:
      enabled: true
    admissionController:
      enabled: true
    liveProcessCollection:
      enabled: true
    liveContainerCollection:
      enabled: true
    clusterChecks:
      enabled: true
      # useClusterChecksRunners: true
    orchestratorExplorer:
      enabled: true
  
  override:
    # Node Agent configuration
    nodeAgent:
      tolerations:
        - operator: Exists

    # Cluster Agent configuration
    clusterAgent:
      replicas: 2