apiVersion: v1
kind: Service
metadata:
  name: shipping-service
spec:
  selector:
    app: shipping-stack
  ports:
  - port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: routes-service
spec:
  selector:
    app: routes-stack
  ports:
  - port: 8000
    targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: tracking-ui
spec:
  type: LoadBalancer
  selector:
    app: tracking-ui
  ports:
  - port: 80
    targetPort: 5000